import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

import GoogleAnalytics from "@/components/google-analytics";
import CookieBanner from "@/components/cookie-banner";

const figtree = Figtree({ subsets: ['latin'], variable: "--figtree", display: "swap" })

export const metadata: Metadata = {
  title: "Kanalservice in Passau",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${figtree.variable} ${figtree.className} antialiased`}>
        <Navbar />
        {children}
        <Footer />

        <GoogleAnalytics GA_MEASUREMENT_ID="G-PNN2RW2675" />
        <CookieBanner />
      </body>
    </html>
  );
}
